### ISSUE TITLE
Setting the `silent` option to true does nothing

### ISSUE THREAD

**Issue by BnayaZil** [getsentry/sentry-webpack-plugin#131]
Setting the `silent` option to true does nothing and this plugin does a lot of noise with the progress bar in Travis.

I use version `1.6.2`.
My setup: 
```
new SentryCliPlugin({
	include: '.',
	ignore: ['node_modules', 'webpack.config.js', 'webpack.dev.config.js', 'webpack.prod.config.js', 'webpack.sdk.config.js'],
	silent: true
})
```

**Comment by kamilogorek** [comment]
It wasn't released yet, sorry 😅 Releasing is in process as I write this. Will be available in `1.7.0`

**Comment by BnayaZil** [comment]
May I offer a PR for that? do u have a spec that I can't count on?

**Comment by kamilogorek** [comment]
@BnayaZil it's already implemented, it just wasn't released. Should work now in 1.7.0

**Comment by BnayaZil** [comment]
After updating to `1.7.0` and with the above settings I'm still seeing the following:
```
> Analyzing 81 sources
> Rewriting sources
> Adding source map references
> Bundled 81 files for upload
> Uploaded release files to Sentry
> File processing complete

Source Map Upload Report
  Scripts
    ~/.eslintrc.js
    ~/__mocks__/fileMock.js
    ~/__mocks__/styleMock.js
    ~/coverage/lcov-report/block-navigation.js
    ~/coverage/lcov-report/sorter.js
    ~/doc/template/publish.js
    ~/doc/template/static/scripts/linenumber.js
    ~/src/__mocks__/brand.js
    ~/src/__mocks__/config.js
    ~/src/__mocks__/language.js
    ~/src/__mocks__/player.js
    ~/src/__mocks__/sdk.js
    ...
    Minified Scripts
    ~/coverage/lcov-report/prettify.js (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/coverage/lcov-report/prettify.js.)
    ~/dist/0.76f83acce35d64e47db5.hot-update.js (no sourcemap ref)
    ...
```

**Comment by kamilogorek** [comment]
It's sentry-cli debug info. See the second part of my previous comment.
